author: Dong Yuanxin

keywords: Hexo, Theme-AD

description: 董沅鑫的小站

# 导航栏头部名称
nav_name: GODBMW

# 导航栏座右铭
motto: "安静写些东西"

github: "https://github.com/dongyuanxin/"

# 站点图标和APP图标
favicon: 
  icon: /images/favicon.ico
  touch_icon: /images/touch-icon.png

# RSS文件位置
rss: 

# 自定义样式文件位置
custom_style: 

# 代码高亮主题
highlight_theme: "night eighties"

# 开启数学公式渲染
mathjax: true

copyright:
  enable: true
  author: "董沅鑫"
  show_link: true
  more: '版权声明: 本博客所有文章除特别声明外, 均采用 <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/">CC BY-NC-SA 4.0</a> 许可协议. 转载请注明出处!'

# 建站时间. 格式：YYYY-MM-DD
start_time: "2018-02-10"

# 如何开启 评论&统计 插件：https://godbmw.com/passages/2018-11-15-theme-bmw-docs-zh/
# 请申请自己的 appid 和 appkey，并且替换下面的 appid 和 appkey
leancloud:
  appid: Hyq9wkH495DgNHWhDQCOfQSp-gzGzoHsz # 填写您的appid
  appkey: WaR7nrzhliHj9aVwdQzkdlGd # 填写您的appkey
  comment: true # 是否开启评论系统
  count: true # 是否开启文章统计

# 需要保证leancloud.comment为true
welcome: 
  enable: true
  interval: 30

# 存放sha256加密的密码
# 拥有所有加锁文章的阅读权限
passwords: 
  - efe07af7441da2b69c4a41e42e73be4db47f66010a56900788a458354a7373ec # godbmw

share:
  twitter: true
  facebook: true
  weibo: true
  qq: true
  wechat: true

analytics:
  baidu:
    enable: false
  google:
    enable: false
    id: 

reward:
  -
    src: /images/wechat.png
    alt: "WeChat"
  -
    src: /images/alipay.png
    alt: "AliPay"

nav:
  -
    name: "首页"
    path: "/"
  -
    name: "归档"
    path: "/archives/"
  -
    name: "标签"
    path: "/tags/"
  -
    name: "分类"
    path: "/categories/"
  -
    name: "友链"
    path: "/friends/"
  -
    name: "关于"
    path: "/about/"

footer:
  - 
    title: "博客推荐"
    children:
      - 
        name: "GodBMW"
        path: "https://godbmw.com/"
      - 
        name: "阮一峰的个人网站"
        path: "http://ruanyifeng.com/"
  -
    title: "系列教程"
    children:
      -
        name: "webpack4系列教程"
        path: "https://godbmw.com/categories/webpack4%E7%B3%BB%E5%88%97%E6%95%99%E7%A8%8B/"
      -
        name: "设计模式手册"
        path: "https://godbmw.com/design-patterns/"
  -
    title: "抓到我"
    children: 
      -
        name: "掘金"
        path: "https://juejin.im/user/5b91fcf06fb9a05d3c7fd4a5"
      -
        name: "思否"
        path: "https://segmentfault.com/"

footer_contact: "Email: yuanxin.me@gmail.com"

friends_avatar_cdn: 
friends:
  -
    nickname: GodBMW
    avatar: /images/friends/godbmw.jpeg
    site: https://godbmw.com/
    meta: 主题作者
    show: true